git:
  depth: false

matrix:
  include:

###############################################################################
# OSX Debug
###############################################################################

    - os: osx
      language: cpp
      osx_image: xcode9.3
      install: 
        - export TZ=Etc/GMT-3
        - brew update
        - brew unlink cmake
        - brew unlink boost 
        - brew install qt5 cmake boost
        - brew link qt5 --force
        - export PATH=/usr/local/opt/qt/bin:$PATH
        - export BEAM_WALLET_UI_IN="BeamWallet-$BEAM_VERSION-Darwin.dmg"
        - export OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
        - export BEAM_WALLET_UI_OUT_VERLESS="Beam-Wallet.dmg"
      env: 
        - BUILD_TYPE=Debug
        - OS_FOLDER=mac
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBRANCH_NAME=$TRAVIS_BRANCH . && make -j 4 && ctest --verbose && cpack;
        - export BEAM_WALLET_UI_OUT="Beam-Wallet-$BEAM_VERSION.dmg"

###############################################################################
# OSX Release
###############################################################################

    - os: osx
      language: cpp
      osx_image: xcode9.3
      install:
        - export TZ=Etc/GMT-3
        - brew update
        - brew unlink cmake
        - brew unlink boost 
        - brew install cmake boost
        - sudo git clone --depth=1 https://github.com/nesbox/qt5-static-mac.git /usr/local/qt5-static
        - export PATH=~/qt5-static/bin:$PATH
        - export OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
        - export QT5_ROOT_DIR="/usr/local/qt5-static"
        - export QML_IMPORT_PATH="/usr/local/qt5-static/qml"
        - export BEAM_WALLET_UI_IN="BeamWallet-$BEAM_VERSION-Darwin.dmg"
        - export BEAM_WALLET_UI_OUT_VERLESS="Beam-Wallet.dmg"
      env: 
        - BUILD_TYPE=Release
        - OS_FOLDER=mac
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDEBUG_MESSAGES_IN_RELEASE_MODE=On -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=$TRAVIS_BRANCH . && make -j 4 && ctest --verbose && cpack;
        - export BEAM_WALLET_UI_OUT="Beam-Wallet-$BEAM_VERSION.dmg"

###############################################################################
# Linux Debug
###############################################################################

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - libssl-dev
            - curl
      install:
        - export TZ=Etc/GMT-3
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
        - sudo apt-get update
        - sudo apt-get install qt510declarative qt510svg libgl1-mesa-dev-lts-xenial
        - eval "CC=gcc-7 && CXX=g++-7"
        - export PATH=/opt/qt510/bin:$PATH
        - export BEAM_WALLET_UI_IN="BeamWallet-$BEAM_VERSION-Linux.deb"
        - export BEAM_WALLET_UI_OUT_VERLESS="Beam-Wallet.deb"
      env: 
        - BUILD_TYPE=Debug
        - OS_FOLDER=linux
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBRANCH_NAME=$TRAVIS_BRANCH . && make -j 4 && ctest --verbose && cpack;
        - export BEAM_WALLET_UI_OUT="Beam-Wallet-$BEAM_VERSION.deb"

###############################################################################
# Linux Release
###############################################################################

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - libssl-dev
            - curl
            - libxi-dev
            - libcups2-dev
      install:
        - export TZ=Etc/GMT-3
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - eval "CC=gcc-7 && CXX=g++-7"
        - git clone --depth=1 https://github.com/nesbox/qt5-static-linux.git /home/travis/qt5-static
        - export QT5_ROOT_DIR="/home/travis/qt5-static"
        - export QML_IMPORT_PATH="/home/travis/qt5-static/qml"
        - export BEAM_WALLET_UI_IN="BeamWallet-$BEAM_VERSION-Linux.deb"
        - export BEAM_WALLET_UI_OUT_VERLESS="Beam-Wallet.deb"
      env: 
        - BUILD_TYPE=Release
        - OS_FOLDER=linux
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDEBUG_MESSAGES_IN_RELEASE_MODE=On -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=$TRAVIS_BRANCH . && make -j 4 && ctest --verbose && cpack;
        - export BEAM_WALLET_UI_OUT="Beam-Wallet-$BEAM_VERSION.deb"

###############################################################################
# Android x86 Release
###############################################################################

    - os: linux
      language: android
      env:
        - ANDROID_ABI=x86
        - BUILD_TYPE=Release
        - ANDROID_SDK_VERSION=23
      android:
        components:
          - tools
          - platform-tools
          - android-23
      install:
        - echo y | sdkmanager "ndk-bundle"
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - sudo git clone --depth=1 https://github.com/nesbox/boost_1_68-android.git /usr/local/boost_1_68-android
        - sudo git clone --depth=1 https://github.com/nesbox/Prebuilt-OpenSSL-Android.git /usr/local/Prebuilt-OpenSSL-Android
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
        - export BOOST_ROOT_ANDROID=/usr/local/boost_1_68-android
        - export OPENSSL_ROOT_DIR_ANDROID=/usr/local/Prebuilt-OpenSSL-Android/Prebuilt
        - export PATH=$ANDROID_NDK_HOME:$PATH
      script:
        - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=$ANDROID_SDK_VERSION -DANDROID_ABI=$ANDROID_ABI -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
        - make wallet-jni -j4
      after_success:
        - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/android-$ANDROID_ABI
        - tar -cvzf libwallet-jni-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/android libwallet-jni.so com
        - curl --retry 3 --ftp-create-dirs -T libwallet-jni-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
        - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/android-$ANDROID_ABI/" libwallet-jni-$BEAM_VERSION.tar.gz

###############################################################################
# Android ARMv7 Release
###############################################################################

    - os: linux
      language: android
      env:
        - ANDROID_ABI=armeabi-v7a
        - BUILD_TYPE=Release
        - ANDROID_SDK_VERSION=23
      android:
        components:
          - tools
          - platform-tools
          - android-23
      install:
        - echo y | sdkmanager "ndk-bundle"
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - sudo git clone --depth=1 https://github.com/nesbox/boost_1_68-android.git /usr/local/boost_1_68-android
        - sudo git clone --depth=1 https://github.com/nesbox/Prebuilt-OpenSSL-Android.git /usr/local/Prebuilt-OpenSSL-Android
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
        - export BOOST_ROOT_ANDROID=/usr/local/boost_1_68-android
        - export OPENSSL_ROOT_DIR_ANDROID=/usr/local/Prebuilt-OpenSSL-Android/Prebuilt
        - export PATH=$ANDROID_NDK_HOME:$PATH
      script:
        - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=$ANDROID_SDK_VERSION -DANDROID_ABI=$ANDROID_ABI -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
        - make wallet-jni -j4
      after_success:
        - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/android-$ANDROID_ABI
        - tar -cvzf libwallet-jni-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/android libwallet-jni.so com
        - curl --retry 3 --ftp-create-dirs -T libwallet-jni-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
        - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/android-$ANDROID_ABI/" libwallet-jni-$BEAM_VERSION.tar.gz

###############################################################################
# Android ARMv8 Release
###############################################################################

    - os: linux
      language: android
      env:
        - ANDROID_ABI=arm64-v8a
        - BUILD_TYPE=Release
        - ANDROID_SDK_VERSION=23
      android:
        components:
          - tools
          - platform-tools
          - android-23
      install:
        - echo y | sdkmanager "ndk-bundle"
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - sudo git clone --depth=1 https://github.com/nesbox/boost_1_68-android.git /usr/local/boost_1_68-android
        - sudo git clone --depth=1 https://github.com/nesbox/Prebuilt-OpenSSL-Android.git /usr/local/Prebuilt-OpenSSL-Android
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
        - export BOOST_ROOT_ANDROID=/usr/local/boost_1_68-android
        - export OPENSSL_ROOT_DIR_ANDROID=/usr/local/Prebuilt-OpenSSL-Android/Prebuilt
        - export PATH=$ANDROID_NDK_HOME:$PATH
      script:
        - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=$ANDROID_SDK_VERSION -DANDROID_ABI=$ANDROID_ABI -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
        - make wallet-jni -j4
      after_success:
        - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/android-$ANDROID_ABI
        - tar -cvzf libwallet-jni-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/android libwallet-jni.so com
        - curl --retry 3 --ftp-create-dirs -T libwallet-jni-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
        - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/android-$ANDROID_ABI/" libwallet-jni-$BEAM_VERSION.tar.gz

###############################################################################
# Common part
###############################################################################

# TODO: version detection should be in one place
before_install:
  - BEAM_VERSION="2.0.$(git rev-list HEAD --count)"

before_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

after_success:
  # deploy using ftp server
  - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER
  - tar -cvzf beam-node-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/beam beam-node beam-node.cfg
  - tar -cvzf beam-wallet-cli-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/wallet beam-wallet beam-wallet.cfg
  - tar -cvzf wallet-api-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/wallet wallet-api wallet-api.cfg
  - tar -cvzf explorer-node-$BEAM_VERSION.tar.gz --directory=$HOME/build/BeamMW/beam/explorer explorer-node explorer-node.cfg
  
  # prep for deploy to AWS S3
  - cp $HOME/build/BeamMW/beam/$BEAM_WALLET_UI_IN $HOME/build/BeamMW/beam/$BEAM_WALLET_UI_OUT
   
  # upload binaries to FTP
  - curl --retry 3 --ftp-create-dirs -T beam-node-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
  - curl --retry 3 --ftp-create-dirs -T beam-wallet-cli-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
  - curl --retry 3 --ftp-create-dirs -T wallet-api-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
  - curl --retry 3 --ftp-create-dirs -T explorer-node-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/
  - curl --retry 3 --ftp-create-dirs -T "$HOME/build/BeamMW/beam/$BEAM_WALLET_UI_IN" "$BUILDS_SERVER_PATH/$BEAM_WALLET_UI_OUT"

  # upload binaries to S3
  - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER/" beam-node-$BEAM_VERSION.tar.gz
  - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER/" beam-wallet-cli-$BEAM_VERSION.tar.gz
  - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER/" wallet-api-$BEAM_VERSION.tar.gz
  - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER/" explorer-node-$BEAM_VERSION.tar.gz
  - artifacts upload --target-paths "$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER/" $HOME/build/BeamMW/beam/$BEAM_WALLET_UI_OUT

notifications:
  email:
    - big.romanov@gmail.com