version: '{build}'
image: Visual Studio 2017

environment:
  BEAM_VERSION_PREFIX: 1.1
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  QT5_ROOT_DIR: c:\beam-libs\qt5-static-win
  QML_IMPORT_PATH: c:\beam-libs\qt5-static-win\qml
  BUILD_SERVER:
    secure: l9RqB2YbSnNIKZqTwnd67BHAXvbjmpj9zcf+YQPi9zfzsVeSysaoLD7gy4gSMjWurk2JVHjRpviw4bBxUbu2sA==  
  BUILD_CONFIG: RelWithDebInfo
  matrix:
    - USE_GPU: On
      GPU_FOLDER: /gpu/
    - USE_GPU: Off
      GPU_FOLDER: /

for:
  - 
    matrix:
      only:
        - USE_GPU: On
    install:
      - cmd: appveyor DownloadFile https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_win10 -FileName cuda.exe    
      - cmd: cuda.exe -s nvcc_10.0 nvprune_10.0 cublas_dev_10.0 cufft_dev_10.0 curand_dev_10.0 cusolver_dev_10.0 cusparse_dev_10.0 nvgraph_dev_10.0 npp_dev_10.0 nvrtc_dev_10.0 nvml_dev_10.0
      - cmd: set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;%PATH%
      - cmd: appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/13794/opencl_runtime_18.1_x64_setup.msi"
      - cmd: start /wait msiexec /i opencl_runtime_18.1_x64_setup.msi /qn  /l*v msiexec2.log

before_build:
  - cmd: git clone --depth=1 https://github.com/BeamMW/libs.git c:/beam-libs
  - cmd: git clone --depth=1 https://github.com/nesbox/qt5-static-win.git c:/beam-libs/qt5-static-win
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH% -DBEAM_USE_GPU=%USE_GPU% -DBEAM_BUILD_JNI=On

test_script:
  - cmd: ctest -C %BUILD_CONFIG% --verbose

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

after_build:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    cpack --verbose -G NSIS -C %BUILD_CONFIG%
    
    git rev-list HEAD --count > BEAM_VERSION_REVISION
    
    set /p BEAM_VERSION_REVISION=<BEAM_VERSION_REVISION
    
    set BEAM_VERSION=%BEAM_VERSION_PREFIX%.%BEAM_VERSION_REVISION%
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-node-%BEAM_VERSION%.zip c:/projects/beam/beam/%BUILD_CONFIG%/beam-node.exe c:/projects/beam/beam/beam-node.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli-%BEAM_VERSION%.zip c:/projects/beam/wallet/%BUILD_CONFIG%/beam-wallet.exe c:/projects/beam/wallet/beam-wallet.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api-%BEAM_VERSION%.zip c:/projects/beam/wallet/%BUILD_CONFIG%/wallet-api.exe
        
    mkdir pack && cd pack && mkdir wallet && mkdir node && mkdir ui && cd ..
    
    mkdir pdb
    
    copy "c:\projects\beam\BeamWallet-%BEAM_VERSION%-win64.exe" "pack\ui\Beam-Wallet.exe"
    
    copy beam\%BUILD_CONFIG%\beam-node.exe pack\node && copy beam\beam-node.cfg pack\node
    
    copy wallet\%BUILD_CONFIG%\beam-wallet.exe pack\wallet && copy wallet\beam-wallet.cfg pack\wallet
    
    7z a c:/projects/beam/beam/beam-pack-%BEAM_VERSION%.zip %CD%\pack\wallet %CD%\pack\node %CD%\pack\ui
    
    7z a c:/projects/beam/beam/beam-pdb-%BEAM_VERSION%.zip "c:/projects/beam/ui/%BUILD_CONFIG%/Beam Wallet.pdb" "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node.pdb" "c:/projects/beam/wallet/%BUILD_CONFIG%/beam-wallet.pdb"

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-node-%BEAM_VERSION%.zip c:\projects\beam\beam-node-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-wallet-cli-%BEAM_VERSION%.zip c:\projects\beam\beam-wallet-cli-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\wallet-api-%BEAM_VERSION%.zip c:\projects\beam\wallet-api-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\beam-pack-%BEAM_VERSION%.zip c:\projects\beam\pack\beam-pack-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\beam-pdb-%BEAM_VERSION%.zip c:\projects\beam\pdb\beam-pdb-%BEAM_VERSION%.zip

    copy c:\projects\beam\BeamWallet-%BEAM_VERSION%-win64.exe c:\projects\beam\Beam-Wallet-%BEAM_VERSION%.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    git rev-list HEAD --count > BEAM_VERSION_REVISION
    
    set /p BEAM_VERSION_REVISION=<BEAM_VERSION_REVISION

    set BEAM_VERSION=%BEAM_VERSION_PREFIX%.%BEAM_VERSION_REVISION%
      
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win%GPU_FOLDER%
              
    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%beam-node-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%beam-wallet-cli-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%wallet-api-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/BeamWallet-%BEAM_VERSION%-win64.exe" "%BUILDS_SERVER_PATH%Beam-Wallet-%BEAM_VERSION%.exe"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/beam-pack-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%pack/beam-pack-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/beam-pdb-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%pdb/beam-pdb-%BEAM_VERSION%.zip"

artifacts:
  - path: beam-node-%BEAM_VERSION%.zip
    name: BeamNode

  - path: beam-wallet-cli-%BEAM_VERSION%.zip
    name: BeamWalletCli

  - path: wallet-api-%BEAM_VERSION%.zip
    name: BeamWalletApi

  - path: pack/beam-pack-%BEAM_VERSION%.zip
    name: BeamPack

  - path: pdb/beam-pdb-%BEAM_VERSION%.zip
    name: BeamPdb

  - path: Beam-Wallet-%BEAM_VERSION%.exe
    name: BeamWallet

deploy:
  provider: S3
  access_key_id:
    secure: J8+/d4TSbhxiaFlDQopFzKbfLPvUy1rMUJlAgnfbBNE=
  secret_access_key:
    secure: sqF9zdsuUm/k9QzY46s250MZJamHjKrwBCAPbinBA/iOJlgLsHC7lq1F5pTr/B+U
  bucket: builds.beam.mw
  region: us-west-2
  unzip: false
  set_public: true
  folder: "%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win%GPU_FOLDER%"
  artifact: BeamPdb, BeamPack, BeamWalletApi, BeamWalletCli, BeamNode, BeamWallet

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
