version: '{build}'
image: Visual Studio 2017

environment:
  BEAM_VERSION_PREFIX: 1.1
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  QT5_ROOT_DIR: c:\beam-libs\qt5-static-win
  QML_IMPORT_PATH: c:\beam-libs\qt5-static-win\qml
  BUILD_SERVER:
    secure: l9RqB2YbSnNIKZqTwnd67BHAXvbjmpj9zcf+YQPi9zfzsVeSysaoLD7gy4gSMjWurk2JVHjRpviw4bBxUbu2sA==  
  BUILD_CONFIG: RelWithDebInfo

before_build:
  - cmd: git clone --depth=1 https://github.com/BeamMW/libs.git c:/beam-libs
  - cmd: git clone --depth=1 https://github.com/nesbox/qt5-static-win.git c:/beam-libs/qt5-static-win
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH% -DBEAM_BUILD_JNI=On

test_script:
  - cmd: ctest -C %BUILD_CONFIG% --verbose

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

after_build:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    cpack --verbose -G NSIS -C %BUILD_CONFIG%
    
    git rev-list HEAD --count > BEAM_VERSION_REVISION
    
    set /p BEAM_VERSION_REVISION=<BEAM_VERSION_REVISION
    
    set BEAM_VERSION=%BEAM_VERSION_PREFIX%.%BEAM_VERSION_REVISION%
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-node-testnet-%BEAM_VERSION%.zip c:/projects/beam/beam/%BUILD_CONFIG%/beam-node-testnet.exe c:/projects/beam/beam/beam-node.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli-testnet-%BEAM_VERSION%.zip c:/projects/beam/wallet/%BUILD_CONFIG%/beam-wallet-testnet.exe c:/projects/beam/wallet/beam-wallet.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api-testnet-%BEAM_VERSION%.zip c:/projects/beam/wallet/%BUILD_CONFIG%/wallet-api-testnet.exe c:/projects/beam/wallet/wallet-api.cfg
        
    mkdir pdb
    
    7z a c:/projects/beam/beam/beam-pdb-testnet-%BEAM_VERSION%.zip "c:/projects/beam/ui/%BUILD_CONFIG%/Beam Wallet Testnet.pdb" "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node-testnet.pdb" "c:/projects/beam/wallet/%BUILD_CONFIG%/beam-wallet-testnet.pdb"

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-node-testnet-%BEAM_VERSION%.zip c:\projects\beam\beam-node-testnet-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-wallet-cli-testnet-%BEAM_VERSION%.zip c:\projects\beam\beam-wallet-cli-testnet-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\wallet-api-testnet-%BEAM_VERSION%.zip c:\projects\beam\wallet-api-testnet-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\beam-pdb-testnet-%BEAM_VERSION%.zip c:\projects\beam\pdb\beam-pdb-testnet-%BEAM_VERSION%.zip

    copy c:\projects\beam\BeamWalletTestnet-%BEAM_VERSION%-win64.exe c:\projects\beam\Beam-Wallet-Testnet-%BEAM_VERSION%.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    git rev-list HEAD --count > BEAM_VERSION_REVISION
    
    set /p BEAM_VERSION_REVISION=<BEAM_VERSION_REVISION

    set BEAM_VERSION=%BEAM_VERSION_PREFIX%.%BEAM_VERSION_REVISION%
      
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win
              
    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node-testnet-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/beam-node-testnet-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli-testnet-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/beam-wallet-cli-testnet-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api-testnet-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/wallet-api-testnet-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/BeamWalletTestnet-%BEAM_VERSION%-win64.exe" "%BUILDS_SERVER_PATH%/Beam-Wallet-Testnet-%BEAM_VERSION%.exe"


    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/beam-pdb-testnet-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/pdb/beam-pdb-testnet-%BEAM_VERSION%.zip"

artifacts:
  - path: beam-node-testnet-%BEAM_VERSION%.zip
    name: BeamNode

  - path: beam-wallet-cli-testnet-%BEAM_VERSION%.zip
    name: BeamWalletCli

  - path: wallet-api-testnet-%BEAM_VERSION%.zip
    name: BeamWalletApi

  - path: pdb/beam-pdb-testnet-%BEAM_VERSION%.zip
    name: BeamPdb

  - path: Beam-Wallet-Testnet-%BEAM_VERSION%.exe
    name: BeamWallet

deploy:
  provider: S3
  access_key_id:
    secure: J8+/d4TSbhxiaFlDQopFzKbfLPvUy1rMUJlAgnfbBNE=
  secret_access_key:
    secure: sqF9zdsuUm/k9QzY46s250MZJamHjKrwBCAPbinBA/iOJlgLsHC7lq1F5pTr/B+U
  bucket: builds.beam.mw
  region: us-west-2
  unzip: false
  set_public: true
  folder: "%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win/"
  artifact: BeamPdb, BeamWalletApi, BeamWalletCli, BeamNode, BeamWallet

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
